// This file should be generated by the FlutterFire CLI.
// Placeholder for DefaultFirebaseOptions. Replace with your actual config.
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, TargetPlatform, kIsWeb;

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      // case TargetPlatform.macOS:
      //   return macos;
      // case TargetPlatform.windows:
      //   return windows;
      // case TargetPlatform.linux:
      //   return linux;
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: "AIzaSyCkasVY3fT1GutCaI5v7EcK3n21RWC01kg",
    authDomain: "my-wedding-app-eb286.firebaseapp.com",
    projectId: "my-wedding-app-eb286",
    storageBucket: "my-wedding-app-eb286.firebasestorage.app",
    messagingSenderId: "228179713430",
    appId: "1:228179713430:web:0a991441f519c385c151b7",
    measurementId: "G-87FJVTLFGM",
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBzMaa1Rais8CFCWtH9dAw2eqaKHfsB_VU',
    appId: '1:228179713430:android:98959e0ec8e23a92c151b7',
    messagingSenderId: '228179713430',
    projectId: 'my-wedding-app-eb286',
    storageBucket: 'my-wedding-app-eb286.firebasestorage.app',
    androidClientId: '228179713430-mvtp6i2be5o71qh5vqqob21bs3tc6kjp.apps.googleusercontent.com',
    // The following are from the JSON config:
    // packageName: 'com.dhanraj.myweddingapp',
    // certificateHash: 'caafc3a4fc48de544e571be9c8a915d4daad82cf',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBDRXJEA6sw0kRNcrhyddiGmrakLlp-WfE',
    appId: '1:228179713430:ios:9f1f855951004234c151b7',
    messagingSenderId: '228179713430',
    projectId: 'my-wedding-app-eb286',
    storageBucket: 'my-wedding-app-eb286.firebasestorage.app',
    iosBundleId: 'com.dhanraj.myweddingapp',
  );

  // static const FirebaseOptions macos = FirebaseOptions(
  //   apiKey: 'dummy-macos-api-key',
  //   appId: '1:1234567890:macos:abcdef123456',
  //   messagingSenderId: '1234567890',
  //   projectId: 'dummy-macos-project-id',
  //   storageBucket: 'dummy-macos.appspot.com',
  //   iosClientId: 'dummy-macos-client-id.apps.googleusercontent.com',
  //   iosBundleId: 'com.example.dummy',
  // );

  // static const FirebaseOptions windows = FirebaseOptions(
  //   apiKey: 'dummy-windows-api-key',
  //   appId: '1:1234567890:windows:abcdef123456',
  //   messagingSenderId: '1234567890',
  //   projectId: 'dummy-windows-project-id',
  //   storageBucket: 'dummy-windows.appspot.com',
  // );

  // static const FirebaseOptions linux = FirebaseOptions(
  //   apiKey: 'dummy-linux-api-key',
  //   appId: '1:1234567890:linux:abcdef123456',
  //   messagingSenderId: '1234567890',
  //   projectId: 'dummy-linux-project-id',
  //   storageBucket: 'dummy-linux.appspot.com',
  // );
}
